name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.4.11
homepage: https://github.com/appsup-dart/openid_client
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter:

dependencies:
  jose:
  pointycastle:
  http:
  logging:
  args:
  meta:
  clock:

dev_dependencies:
  flutter_lints:

executables:
  openid_client: openid_client
