name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.4.11
homepage: https://github.com/appsup-dart/openid_client
funding:
 - https://github.com/sponsors/rbellens

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter:

dependencies:
  jose: ^0.3.2
  pointycastle: ^3.0.0
  http: ^1.2.2
  logging: ^1.0.0
  args: ^2.0.0
  meta: ^1.0.0
  clock: ^1.1.0

dev_dependencies:
  test: ^1.16.5
  lints: ^5.1.0

executables:
  openid_client: openid_client
